### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by bradfodley** [AnshumanSrivastava108/Static-Scantime-Crypter#2]
the encrypted executable file, will it run on windows?

**Comment by AnshumanSrivastava108** [comment]
Yes, it will run on windows.

**Comment by bradfodley** [comment]
actually it didnt work, encrypted executable file gives error, no .net version described

**Comment by AnshumanSrivastava108** [comment]
I hope you have complied it successfully. I have uploaded the raw files.
