### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by caganco** [AnshumanSrivastava108/Static-Scantime-Crypter#3]
There is no output file coming out even tho it says it is created.

**Comment by AnshumanSrivastava108** [comment]
There might be some compilation issue, kindly when it's complied properly. The output file is getting produced.

**Comment by caganco** [comment]
> There might be some compilation issue, kindly when it's complied properly. The output file is getting produced.

well so then can you give me a step to step instruction to opening or compiling your program? because i just opened Main.cpp in dev c++ compiler and compiled then ran it. is there anything i should do with other files?

**Comment by AnshumanSrivastava108** [comment]
I am sorry for the inconvenience you are facing.  Check out this video for step by step procedure - https://player.vimeo.com/video/515842748

**Comment by caganco** [comment]
> I am sorry for the inconvenience you are facing. Check out this video for step by step procedure - https://player.vimeo.com/video/515842748

there's no file named crypter.c or something with a c extension also when i compile the program. all i get is programs with extension of cpp and exe. can you explain me a little bit detailed?

**Comment by seition2** [comment]
> > I am sorry for the inconvenience you are facing. Check out this video for step by step procedure - https://player.vimeo.com/video/515842748
> 
> there's no file named crypter.c or something with a c extension also when i compile the program. all i get is programs with extension of cpp and exe. can you explain me a little bit detailed?

Absolutely 
I couldn't find it eithe

**Comment by AnshumanSrivastava108** [comment]
I suppose there is some issue with the build. I will check and update the files.
